---
resources:
- name: claw
  type: git
  source:
    uri: https://github.com/cloudfoundry/CLAW

- name: claw-pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cli-pws-username}}
    password: {{cli-pws-password}}
    organization: {{cli-pws-org}}
    space: {{cli-pws-space}}
    skip_cert_check: false

jobs:
  - name: test
    plan:
      - get: claw
        trigger: true
      - task: run-test
        config:
          inputs: [name: claw]
          platform: linux
          image: docker:///ruby
          run:
            path: claw/ci/scripts/run-test.sh

  - name: deploy
    plan:
      - get: claw
        passed: [test]
      - put: claw-pws
        params:
          manifest: claw/manifest.yml
          path: claw
          current_app_name: claw
