---
resources:
- name: claw
  type: git
  source:
    uri: https://github.com/cloudfoundry/CLAW

- name: claw-pws-pivotal
  type: cf
  source:
    api: https://api.run.pivotal.io
    client_id: {{cli-pws-client-id}}
    client_secret: {{cli-pws-client-secret}}
    organization: {{cli-pws-organization}}
    space: {{cli-pws-space}}
    skip_cert_check: false

- name: claw-pws-oss
  type: cf
  source:
    api: https://api.run.pivotal.io
    client_id: {{cli-pws-client-id}}
    client_secret: {{cli-pws-client-secret}}
    organization: {{cli-pws-oss-organization}}
    space: {{cli-pws-oss-space}}
    skip_cert_check: false

jobs:
  - name: test
    plan:
      - get: claw
        trigger: true
      - task: run-test
        config:
          inputs: [name: claw]
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: slim
          run:
            path: claw/ci/scripts/run-test.sh

  - name: deploy
    plan:
      - get: claw
        passed: [test]
        trigger: true
      - put: claw-pws-pivotal
        params:
          manifest: claw/manifest-pivotal.yml
          path: claw
          vars:
            CURRENT_MAJOR_VERSION: v6
      - put: claw-pws-oss
        params:
          manifest: claw/manifest-oss.yml
          path: claw
          vars:
            CURRENT_MAJOR_VERSION: v6
