---
resource_types:
  - name: cf-cli-resource
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource
      tag: latest

resources:
- name: claw
  type: git
  source:
    uri: https://github.com/cloudfoundry/CLAW
    branch: {{git-branch}}

- name: claw-pws-pivotal
  type: cf-cli-resource
  source:
    api: https://api.run.pivotal.io
    client_id: {{cli-pws-client-id}}
    client_secret: {{cli-pws-client-secret}}
    org: {{pivotal-organization}}
    space: {{pivotal-space}}
    skip_cert_check: false

- name: claw-pws-oss
  type: cf-cli-resource
  source:
    api: https://api.run.pivotal.io
    client_id: {{cli-pws-client-id}}
    client_secret: {{cli-pws-client-secret}}
    org: {{oss-organization}}
    space: {{oss-space}}
    skip_cert_check: false

jobs:
  - name: test
    plan:
      - get: claw
        trigger: true
      - task: run-test
        config:
          inputs: [name: claw]
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: slim
          run:
            path: claw/ci/scripts/run-test.sh

  - name: deploy
    plan:
      - get: claw
        passed: [test]
        trigger: true
      - put: claw-pws-pivotal
        params:
          command: push
          manifest: {{manifest-pivotal}}
          path: claw
          vars:
            CURRENT_MAJOR_VERSION: v6
      - put: claw-pws-oss
        params:
          command: push
          manifest: {{manifest-oss}}
          path: claw
          vars_file:
            - claw/claw-variables.yml
